sonar.projectKey=portfolio-app
sonar.projectName=Portfolio App
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,dist/**,public/**

sonar.host.url=http://localhost:9000
sonar.login=squ_535e970e151dbf2e29a63fb97f7659e9d39dde30
